// Generated by CoffeeScript 1.6.3
(function() {
  tetra.start();

  tetra.view.register('formView', {
    scope: 'truc',
    constr: function(me, app, _) {
      return {
        events: {
          user: {
            "submit": {
              "form": function(e, elm) {
                return app.notify("user input", elm.serialize());
              }
            }
          },
          controller: {
            "show filtered data": function(data) {
              return me.output.html(data);
            }
          }
        },
        methods: {
          init: function() {
            return me.output = _("#outputFld");
          }
        }
      };
    }
  });

  tetra.controller.register('formController', {
    scope: 'truc',
    constr: function(me, app, _) {
      return {
        events: {
          view: {
            "user input": function(data) {
              return app.notify("show filtered data", data);
            }
          }
        }
      };
    }
  });

}).call(this);
