// Generated by CoffeeScript 1.6.3
(function() {
  tetra.start();

  tetra.view.register('formView', {
    scope: 'truc',
    constr: function(me, app, _) {
      return {
        events: {
          user: {
            "keyup": {
              "#inputFld": function(e, elm) {
                return me.output.html(elm.val());
              }
            }
          }
        },
        methods: {
          init: function() {
            return me.output = _("#outputFld");
          }
        }
      };
    }
  });

}).call(this);
